# Generated by Django 5.1.2 on 2025-03-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('sexo', models.BooleanField(default=False, help_text='0=Mujer, 1=Hombre')),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=100)),
                ('direccion', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('huella_digital', models.ImageField(blank=True, null=True, upload_to='huellas/')),
                ('huella_hex', models.TextField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
